# -*- coding: utf-8 -*-
"""python_class_2_assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wdn7s7cIsbXHmOhiJWQPUuKbWkzjCqom
"""

#Simple Calculator

number_1 = int(input("Enter your first number: "))
number_2 = int(input("Enter your second number: "))
operator = input("Select operator (+, -, *, /, %, **, //): ")

if operator == "+":
    print(f"Result of {number_1} + {number_2} is: {number_1 + number_2}")
elif operator == "-":
    print(f"Result of {number_1} - {number_2} is: {number_1 - number_2}")
elif operator == "*":
    print(f"Result of {number_1} * {number_2} is: {number_1 * number_2}")
elif operator == "/":
    print(f"Result of {number_1} / {number_2} is: {number_1 / number_2}")
elif operator == "%":
    print(f"Result of {number_1} % {number_2} is: {number_1 % number_2}")
elif operator == "**":
    print(f"Result of {number_1} ** {number_2} is: {number_1 ** number_2}")
elif operator == "//":
    print(f"Result of {number_1} // {number_2} is: {number_1 // number_2}")
else:
    print("Invalid operator! Please enter a valid one.")

print("\nMade by Taha Saif")

# Student Marks Based Grading System
marks = int(input("Enter your marks (0-100): "))

if marks >= 80:
    grade = 'A'
    feedback = "Excellent! Keep up the great work!"
elif marks >= 70:
    grade = 'B'
    feedback = "Good job! You can aim for even higher achievements."
elif marks >= 60:
    grade = 'C'
    feedback = "Fair effort! Try to improve more and do more hard work."
elif marks >= 50:
    grade = 'D'
    feedback = "You passed, but there's need for improvement."
else:
    grade = 'F'
    feedback = "Unfortunately, you failed. Don't give up! Keep trying."

print(f"Your Grade: {grade}")
print(feedback)
print("\nMade by Taha Saif")

"""**Some Other Assignments I did for my own practise **"""

#Advanced Student Marks Based Grading System
print("📚 Welcome to the Student Grading System!")

#initial total marks
total_marks = 0

math = float(input("Enter marks for Math (out of 100): "))
science = float(input("Enter marks for Science (out of 100): "))
english = float(input("Enter marks for English (out of 100): "))
computer = float(input("Enter marks for Computer (out of 100): "))
physics = float(input("Enter marks for Physics (out of 100): "))

total_marks = math + science + english + computer + physics
percentage = (total_marks / 500) * 100

# Determining the students grade based on their percentage
if percentage >= 80:
    grade = 'A'
    feedback = "Excellent! Keep up the great work!"
elif percentage >= 70:
    grade = 'B'
    feedback = "Good job! You can aim for even higher achievements."
elif percentage >= 60:
    grade = 'C'
    feedback = "Fair effort! Try to improve more and do more hard work."
elif percentage >= 50:
    grade = 'D'
    feedback = "You passed, but there's need for improvement."
else:
    grade = 'F'
    feedback = "Unfortunately, you failed. Don't give up! Keep trying."

# Results
print("\nResults:")
print(f"Total Marks: {total_marks} / 500")
print(f"Percentage: {percentage:.2f}%") #.2f is for 2 digit after point
print(f"Your Grade: {grade}")
print(feedback)

print("\nMade by Taha Saif")

#3. Login System (Username & Password) If and Elif
username = input("Enter your username: ")
password = input("Enter your password: ")
attempts = 3

if username == "admin" and password == "admin1234":
  print("Access granted. Welcome, admin!")
else:
  print(f"Welcome! user {username}")
print("\nMade by Taha Saif")

#4. Even or Odd Number Checker If and Elif
number = int(input("Enter a number to check is it even or odd: "))

if number % 2 == 0:
    print(f"Number {number} is Even")
elif number % 2 != 0:
   print(f"Number {number} is Odd")
else:
   print("Invalid input. Please enter a valid number.")
print("\nMade by Taha Saif")

#5. Age Verification for Voting System
age = int(input("Enter your age: "))

if age >= 18:
  print("you are eligible to vote")
elif age < 18:
  print("you are not eligible to vote")
else:
  print("Invalid input. Please enter a valid age.")
print("\nMade by Taha Saif")

#6. Number Comparison Game
number_1 = int(input("Enter first number: "))
number_2 = int(input("Enter second number: "))

if number_1 > number_2:
  print(f"Number {number_1} is greater than {number_2}")
elif number_1 < number_2:
  print(f"Number {number_1} is less than {number_2}")
else:
  print(f"Number {number_1} is equal to {number_2}")

print("\nMade by Taha Saif")

#7. Age Category Checker
age = int(input("Enter your age: "))

if age >=0 and age <=12:
  print("You are a Child")
elif age >=13 and age <=19:
  print("You are a Teenager")
elif age >=20 and age <=59:
  print("You are an Adult")
elif age >=60:
  print("You are a Senior Citizen")
else:
  print("Invalid input. Please enter a valid age.")
print("\nMade by Taha Saif")

#8. Shopping Discount Calculator
total_bill = float(input("Enter the total price of items: "))

if total_bill >=5000:
  discount = 0.20
elif total_bill >=3000:
  discount = 0.15
elif total_bill >=1000:
  discount = 0.10
else:
  discount = 0.0

discount = total_bill * discount
final_bill = total_bill - discount

print(f"Total Bill: ${total_bill:.0f}")
print(f"Discount: ${discount:.0f}")
print(f"Final Bill after Discount: ${final_bill:.0f}")

#9. Mini Quiz App
print("Welcome to the Mini Quiz App!")
print("Answer the following questions to test your knowledge.")

score = 0
total_questions = 5

answer1 = input("1. What is the capital of France? \n(a) Paris \n(b) London \nYour answer: ").lower()
if answer1 == "a" or answer1 == "paris":
    score += 1

answer2 = input("2. What is the largest planet in our solar system? \n(a) Jupiter \n(b) Saturn \nYour answer: ").lower()
if answer2 == "a" or answer2 == "jupiter":
    score += 1

answer3 = input("3. What is the chemical symbol for gold? \n(a) Au \n(b) Ag \nYour answer: ").lower()
if answer3 == "a" or answer3 == "au":
    score += 1

answer4 = input("4. What is the smallest country in the world? \n(a) Vatican City \n(b) Monaco \nYour answer: ").lower()
if answer4 == "a" or answer4 == "vatican city":
    score += 1

answer5 = input("5. What is the largest country in the world by land area? \n(a) Russia \n(b) Canada \nYour answer: ").lower()
if answer5 == "a" or answer5 == "russia":
    score += 1

final_score = (score / total_questions) * 100

print("\nQuiz Results:")
print(f"Total Questions: {total_questions}")
print(f"Correct Answers: {score}")

#Feedback
if score == 5:
    print("Excellent! You got all answers correct!")
elif score >= 3:
    print("Good Job! You did well!")
else:
    print("Keep Practicing! You'll get better!")

print("\nThank you for playing! - Made by Taha Saif")

#10. Number Guessing Game
import random

print("Welcome to the Number Guessing Game!")
secret_number = random.randint(1, 100)
guess_number = int(input("Guess a number between 1 and 100: "))

# Checking the user guesses
if guess_number == secret_number:
    print("Congratulations! You guessed the correct number!")
elif guess_number < secret_number:
    print("Too low!")
    print("The correct number was:", secret_number)
else:
    print("Too high!")
    print("The correct number was:", secret_number)
print("\nGame Over - Made by Taha Saif")

#11. Leap year check
year = 2000
if year % 4 == 0 and year % 100 == 0 and year % 400 == 0:
  print("Leap Year")
else:
  print('Not Leap Year')